** Privacy Policy
   :PROPERTIES:
   :CUSTOM_ID: privacy-policy
   :END:
The privacy of my visitors is extremely important. This Privacy Policy
outlines the types of personal information that is received and
collected and how it is used.

First and foremost, I will never share your email address or any other
personal information to anyone without your direct consent.

I. Definitions

The privacy policy of the Max Delbrück Center for Molecular Medicine is
based on the terms used by the European legislator in the adoption of
the Basic Regulation on Data Protection (DSGVO). Our data protection
declaration should be easy to read and understand both for the public
and for our customers and business partners. To ensure this, we would
like to explain the terms used in advance.

In this privacy policy we use the following terms, among others:

personal data\\
  Personal data is all information relating to an identified or
identifiable natural person (hereinafter referred to as "data subject").
Identifiable is a natural person who can be identified directly or
indirectly, in particular by assignment to an identifier such as a name,
an identification number, location data, an online identifier or one or
more special characteristics that express the physical, physiological,
genetic, psychological, economic, cultural or social identity of that
natural person.\\
person affected\\
   Data subject is any identified or identifiable natural person whose
personal data are processed by the controller.\\
Processing\\
   Processing means any operation or series of operations carried out
with or without the aid of automated procedures relating to personal
data, such as the collection, collection, organization, filing, storage,
adaptation or modification, retrieval, querying, use, disclosure by
transmission, dissemination or any other form of provision,
reconciliation or linking, restriction, deletion or destruction.\\
Restricting processing\\
   Restriction on processing is the marking of stored personal data with
the aim of restricting their future processing.\\
Pseudonymization\\
   Pseudonymization is the processing of personal data in such a way
that the personal data can no longer be assigned to a specific data
subject without additional information, provided that this additional
information is kept separately and is subject to technical and
organizational measures that ensure that the personal data is not
assigned to an identified or identifiable natural person.\\
person in charge or person responsible for processing\\
   The controller or controller shall be the natural or legal person,
authority, body, office or other body which alone or jointly with others
decides on the purposes and means of processing personal data. Where the
purposes and means of such processing are laid down by Union law or by
the law of the Member States, the controller or the specific criteria
for his appointment may be laid down in accordance with Union law or the
law of the Member States.\\
Order processor\\
   Processor is a natural or legal person, authority, institution or
other body that processes personal data on behalf of the data
controller.\\
receiver\\
   The recipient is a natural or legal person, authority, institution or
other body to which personal data is disclosed, whether or not it is a
third party. However, authorities which may receive personal data under
Union law or the law of the Member States within the framework of a
particular investigation mandate shall not be regarded as recipients.\\
Thirds\\
   Third party is a natural or legal person, authority, institution or
other body other than the data subject, the data processor, the data
processor and the persons authorised to process the personal data under
the direct responsibility of the data processor or the data processor.\\
agreement\\
   Acceptance is any informed and unequivocal statement of intent, in
the form of a statement or other clear affirmative act, voluntarily
given by the data subject for the particular case, that the data subject
indicates his or her consent to the processing of personal data
concerning him or her.

2. Name and address of the person responsible

The person responsible within the meaning of the Basic Data Protection
Regulation and other national data protection laws of the member states
and other data protection regulations is:

Kyle Harrington\\
Robert Rössle St. 10\\
13125 Berlin\\
Germany

Tel.: 030-94062195

Website: www.kyleharrington.com

3. Name and address of the data protection officer

The data protection officer of the person responsible is:

Kyle Harrington\\
Email: Datenschutz@kyleharrington.com\\
Website: www.kyleharrington.com

4. General information about data processing

scope of processing of personal data

We only process personal data of our users if this is necessary to
provide a functional website as well as our contents and services. The
processing of personal data of our users takes place regularly only
after consent of the user. An exception applies in those cases where
prior consent cannot be obtained for real reasons and the processing of
the data is permitted by law. Legal basis for the processing of personal
data

Insofar as we obtain the consent of the data subject for the processing
of personal data, Article 6(1)(a) of the EU Data Protection Ordinance
(DSGVO) serves as the legal basis.

For the processing of personal data necessary for the performance of a
contract to which the data subject is a party, Article 6(1)(b) DSGVO
serves as the legal basis. This also applies to processing operations
that are necessary to carry out pre-contractual measures.

To the extent that processing of personal data is necessary to fulfil a
legal obligation to which our company is subject, Article 6(1)(c) DSGVO
serves as the legal basis.

In the event that the vital interests of the data subject or another
natural person require the processing of personal data, Article 6(1)(d)
DSBER serves as the legal basis.

If processing is necessary to safeguard a legitimate interest of our
company or a third party and if the interests, fundamental rights and
freedoms of the data subject do not outweigh the former interest,
Article 6(1)(f) DSGVO serves as the legal basis for processing.

3 -- data erasure and storage time

The personal data of the person concerned will be deleted or blocked as
soon as the purpose of storage ceases to apply. Furthermore, data may be
stored if this has been provided for by the European or national
legislator in EU regulations, laws or other provisions to which the
person responsible is subject. The data will also be blocked or deleted
if a storage period prescribed by the aforementioned standards expires,
unless there is a need for further storage of the data for the
conclusion or fulfilment of a contract.

V. Provision of the website and creation of log files

1 -- description and scope of data processing

Every time you visit our website, our system automatically collects data
and information from the computer system of the calling computer.

The following data are collected:

#+begin_example
  Internet Protocol addresses (IP)
  Types of browser
  Internet Service Provider (ISP)
  Date and time stamp
  Referring and exit pages
  Number of clicks
#+end_example

The data is also stored in the log files of our system. This data is not
stored together with other personal data of the user.

2 -- legal basis for data processing

The legal basis for the temporary storage of data and log files is Art.
6 para.1 lit. f DSGVO.

3 -- purpose of data processing

The temporary storage of the IP address by the system is necessary to
enable the website to be delivered to the user's computer. For this the
IP address of the user must remain stored for the duration of the
session.

The data is stored in log files to ensure the functionality of the
website. In addition, the data serves us to optimize the website and to
ensure the security of our information technology systems. An evaluation
of the data for marketing purposes does not take place in this context.

In these purposes is also our legitimate interest in data processing
according to Art. 6 para.1 lit. f DSGVO.

4 -- storage time

The data will be deleted as soon as it is no longer necessary to achieve
the purpose of its collection. In the case of the collection of data for
the provision of the website, this is the case when the respective
session has ended.

The controller shall process and store the personal data of the data
subject only for the time necessary to achieve the data retention
purpose or as provided for by the European regulator or other legislator
in laws or regulations to which the controller is subject.

If the storage purpose is not fulfilled or if a storage period
prescribed by the European Directive and Regulation Giver or another
competent legislator expires, the personal data will be blocked or
deleted routinely and in accordance with the statutory provisions.

5 -- possibility of objection and elimination

The collection of data to provide the website and the storage of data in
log files is mandatory for the operation of the website. Consequently,
there is no possibility of objection on the part of the user.

6. Use of Cookies

1 -- description and scope of data processing

Our website uses cookies. Cookies are text files that are stored in the
Internet browser or by the Internet browser on the user's computer
system. If a user visits a website, a cookie may be stored on the user's
operating system. This cookie contains a characteristic character string
that enables a unique identification of the browser when the website is
called up again.

When you visit this site cookies are stored on your computer to identify
trusted traffic, which are used by the content network, Cloudflare. This
prevents attacks and enables secure access to the website. For more
information you can read Cloudflare's
[[https://www.cloudflare.com/privacypolicy][privacy policy]] and
[[https://www.cloudflare.com/terms/][terms of service]].

2 -- legal basis for data processing

The legal basis for the processing of personal data using cookies is
Article 6(1)(f) DSGVO.

3 -- purpose of data processing

The purpose of using technically necessary cookies is to simplify the
use of websites for users. Some functions of our website cannot be
offered without the use of cookies. For this it is necessary that the
browser is recognized even after a page change.

The user data collected by technically necessary cookies are not used to
create user profiles.

For these purposes, our legitimate interest also lies in the processing
of personal data in accordance with Article 6(1)(f) DSGVO.

4 -- Duration of storage, objection and elimination option

Cookies are stored on the user's computer and transmitted to our site by
the user. Therefore, you as a user also have full control over the use
of cookies. You can deactivate or restrict the transmission of cookies
by changing the settings in your Internet browser. Cookies that have
already been saved can be deleted at any time. This can also be done
automatically. If cookies are deactivated for our website, it may no
longer be possible to use all functions of the website in full.

*** Google Analytics
    :PROPERTIES:
    :CUSTOM_ID: google-analytics
    :END:
Google Analytics is a web analytics tool I use to help understand how
visitors engage with this website. It reports website trends using
cookies and web beacons without identifying individual visitors. For
more information you can read the
[[http://www.google.com/analytics/learn/privacy.html][Google Analytics
Privacy Policy]].

*** Rights of the person concerned
    :PROPERTIES:
    :CUSTOM_ID: rights-of-the-person-concerned
    :END:
If personal data are processed by you, you are affected by the DSGVO and
you have the following rights against the person responsible:

*right to information*

You can ask the data controller to confirm whether personal data
concerning you is being processed by us.

If such processing exists, you can ask the person responsible to provide
the following information:

#+begin_example
  the purposes for which the personal data are processed;
  the categories of personal data being processed;
  the recipients or categories of recipients to whom the personal information about you has been or will be disclosed;
  the planned duration of the storage of personal data concerning you or, if specific information on this is not possible, criteria for the determination of the storage period;
  the existence of a right of rectification or deletion of personal data concerning you, of a right of limitation of the processing by the controller or of a right of objection to such processing;
  the existence of a right of appeal to a supervisory authority;
  all available information on the origin of the data if the personal data is not collected from the data subject;
  the existence of automated decision-making, including profiling in accordance with Articles 22(1) and (4) DSBER and - at least in these cases - meaningful information on the logic involved and the scope and intended effects of such processing for the data subject.
#+end_example

You have the right to request information as to whether the personal
data concerning you is transferred to a third country or to an
international organisation. In this context, you may request to be
informed of the appropriate guarantees in accordance with Art. 46 DSGVO
in connection with the transmission.

*right to correction*

You have the right to correct and/or complete any personal data
processed concerning you that is incorrect or incomplete. The person
responsible shall make the correction without delay.

*right to limitation of processing*

You may request that the processing of personal data concerning you be
restricted under the following conditions:

#+begin_example
  if you dispute the accuracy of the personal data concerning you for a period of time that allows the data controller to verify the accuracy of the personal data;
  the processing is unlawful and you refuse to delete the personal data and instead request the restriction of the use of the personal data;
  the data controller no longer needs the personal data for the purposes of the processing, but you need it to assert, exercise or defend legal claims, or
  if you have filed an objection to the processing pursuant to Art. 21 para. 1 DSGVO and it has not yet been determined whether the legitimate reasons of the person responsible outweigh your reasons.
#+end_example

If the processing of personal data concerning you has been restricted,
such data may only be processed - apart from being stored - with your
consent or for the purpose of asserting, exercising or defending rights
or for the protection of the rights of another natural or legal person
or on grounds of an important public interest of the Union or a Member
State.

If the processing restriction is restricted according to the above
conditions, you will be informed by the person responsible before the
restriction is removed.

*right of deletion*

1) Duty to delete

You may request the data controller to delete the personal data
concerning you immediately and the data controller is obliged to delete
this data immediately if one of the following reasons applies:

#+begin_example
  The personal information about you is no longer necessary for the purposes for which it was collected or otherwise processed.
  You revoke your consent on which the processing was based in accordance with Article 6(1)(a) or Article 9(2)(a) of the DSGVO, and there is no other legal basis for the processing.
  You file an objection against the processing pursuant to Art. 21 para. 1 DSBER and there are no overriding legitimate grounds for processing, or you file an objection against the processing pursuant to Art. 21 para. 2 DSBER.
  The personal data concerning you has been processed unlawfully.
  The deletion of personal data concerning you is necessary to fulfil a legal obligation under Union law or the law of the Member States to which the data controller is subject.
  The personal data concerning you have been collected in relation to information society services offered pursuant to Art. 8 para. 1 DSGVO.
#+end_example

2) Information to third parties

If the data controller has made the personal data concerning you public
and is obliged to delete them in accordance with Article 17(1) of the
DSGVO, he shall take appropriate measures, including technical measures,
taking into account the technology available and the implementation
costs, to inform data processors who process the personal data that you
as the data subject have requested the deletion of all links to this
personal data or of copies or replications of this personal data. c)
Exceptions

The right to cancellation does not exist if the processing is necessary

#+begin_example
  for the exercise of the right to freedom of expression and information;
  to fulfil a legal obligation required for processing under the law of the Union or of the Member States to which the controller is subject, or to perform a task in the public interest or in the exercise of official authority conferred on the controller;
  for reasons of public interest in the field of public health in accordance with Article 9(2)(h) and (i) and Article 9(3) DSGVO;
  for archiving purposes in the public interest, scientific or historical research purposes or for statistical purposes according to Art. 89 para. 1 DSGVO, insofar as the law mentioned under a) is likely to make it impossible or seriously impair the attainment of the objectives of such processing, or
  for asserting, exercising or defending legal claims.
#+end_example

*right to information*

If you have exercised your right of rectification, deletion or
limitation of processing against the controller, the controller is
obliged to notify all recipients to whom the personal data concerning
you have been disclosed of such rectification or deletion or restriction
of processing, unless this proves impossible or involves
disproportionate effort.

You have the right vis-à-vis the person responsible to be informed about
these recipients.

*right to data transferability*

You have the right to receive the personal information about you that
you have provided to the owner in a structured, common and
machine-readable format. In addition, you have the right to transmit
this data to another person in charge without obstruction by the person
in charge to whom the personal data was provided, provided

#+begin_example
  the processing is based on a consent pursuant to Art. 6 para.1 lit. a DSGVO or Art. 9 para.2 lit. a DSGVO or on a contract pursuant to Art. 6 para. 1 lit. b DSGVO and
  processing is carried out using automated methods.
#+end_example

In exercising this right, you also have the right to have the personal
data concerning you transferred directly from one data controller to
another data controller, insofar as this is technically feasible. The
freedoms and rights of other persons must not be affected by this.

The right to data transfer shall not apply to the processing of personal
data necessary for the performance of a task in the public interest or
in the exercise of official authority conferred on the controller.

*right of objection*

You have the right to object at any time, for reasons arising from your
particular situation, to the processing of personal data concerning you
in accordance with Article 6(1)(e) or (f) of the DSGVO, including
profiling based on these provisions.

The controller no longer processes the personal data concerning you
unless he can prove compelling grounds for processing that outweigh your
interests, rights and freedoms or the processing serves to assert,
exercise or defend legal claims.

If personal data concerning you are processed for direct marketing
purposes, you have the right to object at any time to the processing of
personal data concerning you for the purpose of such advertising,
including profiling, in so far as it is related to such direct
marketing.

If you object to the processing for direct marketing purposes, the
personal data concerning you will no longer be processed for these
purposes.

You have the option of exercising your right of opposition in connection
with the use of Information Society services through automated
procedures using technical specifications, notwithstanding Directive
2002/58/EC.

*right to revoke the data protection declaration of consent*

You have the right to revoke your data protection consent at any time.
The revocation of consent shall not affect the legality of the
processing carried out on the basis of the consent until revocation.

*right of appeal to a regulatory authority*

Without prejudice to any other administrative or judicial remedy, you
have the right of appeal to a supervisory authority, in particular in
the Member State where you reside, work or suspect of infringement, if
you believe that the processing of personal data concerning you is
contrary to the DSGVO.

The supervisory authority to which the complaint was lodged informs the
complainant of the status and the results of the complaint, including
the possibility of a judicial remedy under Article 78 DSGVO.

Updated: October 23, 2020
